# Generated by Django 5.0.6 on 2024-07-22 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_interest_name_alter_skill_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interest',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='userinterest',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='userskill',
            options={'ordering': ['-id']},
        ),
    ]
