import os

USER_SERVICE_URL = os.getenv('USER_SERVICE_URL')
ARTICLE_SERVICE_URL = os.getenv('ARTICLE_SERVICE_URL')
COMMUNITY_SERVICE_URL = os.getenv('COMMUNITY_SERVICE_URL')
TEAM_SERVICE_URL = os.getenv('TEAM_SERVICE_URL')
COMMUNICATION_SERVICE_URL = os.getenv('COMMUNICATION_SERVICE_URL')
COMMUNICATION_SERVICE_WS_URL = os.getenv('COMMUNICATION_SERVICE_WS_URL')
PAYMENT_SERVICE_URL = os.getenv('PAYMENT_SERVICE_URL')  

 