# Generated by Django 5.0.7 on 2024-08-08 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0003_alter_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(related_name='team_meetings', to='team_app.user')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='team_app.team')),
            ],
            options={
                'ordering': ['-start_time'],
            },
        ),
    ]
