version: '3.8'

services:
  api_gateway:
    container_name: api_gateway
    build: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - user_service
      - article_service
      - community_service
      - team_service
      - communication_service
    volumes:
      - ./api_gateway:/app

  user_service:
    container_name: user_service
    build: ./user_service
    ports:
      - "8001:8001"
    depends_on:
      - user_db
      - user_redis
      - kafka
    volumes:
      - ./user_service:/app

  article_service:
    container_name: article_service
    build: ./article_service
    ports:
      - "8002:8002"
    depends_on:
      - article_db
      - kafka
    volumes:
      - ./article_service:/app

  community_service:
    container_name: community_service
    build: ./community_service
    ports:
      - "8003:8003"
    depends_on:
      - community_db
      - kafka
    volumes:
      - ./community_service:/app

  team_service:
    container_name: team_service
    build: ./team_service
    ports:
      - "8004:8004"
    depends_on:
      - team_db
      - kafka
    volumes:
      - ./team_service:/app

  communication_service:
    container_name: communication_service
    build: ./communication_service
    ports:
      - "8005:8005"
    depends_on:
      - communication_db
      - communication_redis
      - kafka
    volumes:
      - ./communication_service:/app

  payment_service:
    container_name: payment_service
    build: ./payment_service
    ports:
      - "8006:8006"
    depends_on:
      - payment_db
      - kafka
    volumes:
      - ./payment_service:/app

  user_db:
    container_name: user_db
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${USER_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - user_db_data:/var/lib/postgresql/data

  article_db:
    container_name: article_db
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${ARTICLE_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - article_db_data:/var/lib/postgresql/data

  community_db:
    container_name: community_db
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${COMMUNITY_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - community_db_data:/var/lib/postgresql/data

  team_db:
    container_name: team_db
    image: postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: ${TEAM_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - team_db_data:/var/lib/postgresql/data

  communication_db:
    container_name: communication_db
    image: postgres
    ports:
      - "5436:5432"
    environment:
      POSTGRES_DB: ${COMMUNICATION_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - communication_db_data:/var/lib/postgresql/data

  payment_db:
    container_name: payment_db
    image: postgres
    ports:
      - "5437:5432"
    environment:
      POSTGRES_DB: ${PAYMENT_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - payment_db_data:/var/lib/postgresql/data

  user_redis:
    container_name: user_redis
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - user_redis_data:/data

  communication_redis:
    container_name: communication_redis
    image: "redis:alpine"
    ports:
      - "6380:6379"
    volumes:
      - communication_redis_data:/data

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_LOG4J_PROP=log4j.rootLogger=OFF, stdout

  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LOG4J_OPTS=-Dlog4j.rootLogger=OFF
    depends_on:
      - zookeeper
    restart: on-failure

  celery-worker:
    container_name: celery_worker
    build: ./communication_service
    command: celery -A communication_service worker -l info
    depends_on:
      - communication_db
      - communication_redis
      - kafka
    volumes:
      - ./communication_service:/app
    environment:
      - CELERY_BROKER_URL=kafka://host.docker.internal:9092
      - CELERY_RESULT_BACKEND=django-db
      - CELERY_CACHE_BACKEND=django-cache
      - CELERY_ACCEPT_CONTENT=json
      - CELERY_TASK_SERIALIZER=json
      - CELERY_RESULT_SERIALIZER=json
      - CELERY_TIMEZONE=Asia/Kolkata

  stripe-cli:
    container_name: stripe_cli_container
    image: stripe/stripe-cli:latest
    entrypoint: /bin/sh
    command: -c "stripe listen --forward-to http://host.docker.internal:8000/api/payments/webhook/"
    volumes:
      - ./payment_service:/app
    tty: true  # Keep the terminal open

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command: --config.file /etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    restart: always

volumes:
  user_db_data:
  article_db_data:
  community_db_data:
  team_db_data:
  communication_db_data:
  payment_db_data:
  user_redis_data:
  communication_redis_data:
  kafka_data:
  zookeeper_data:
  prometheus_data:
  grafana_data: