# Generated by Django 5.0.7 on 2024-07-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='community_covers/'),
        ),
        migrations.AlterField(
            model_name='community',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='community_profiles/'),
        ),
    ]
