# Generated by Django 5.0.7 on 2024-08-02 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='teammember',
            options={'ordering': ['-created_at']},
        ),
    ]
