# Generated by Django 5.0.7 on 2024-08-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_app', '0004_teammeeting'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammeeting',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterField(
            model_name='team',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='team_service/team_app/profiles/'),
        ),
    ]
