# Generated by Django 5.0.6 on 2024-07-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
