# Generated by Django 5.0.6 on 2024-07-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0007_alter_comment_options_alter_like_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
