# Generated by Django 5.0.8 on 2024-08-10 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_teammember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
