# Generated by Django 5.0.8 on 2024-08-18 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_message_file_alter_message_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='profile_image',
            field=models.CharField(blank=True, null=True),
        ),
    ]
