# Generated by Django 5.0.8 on 2024-08-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_team_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, null=True),
        ),
    ]
