# Generated by Django 5.0.7 on 2024-08-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0003_alter_community_options_community_rules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
