# Generated by Django 5.0.7 on 2024-08-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_app', '0004_alter_community_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='community_service/community_app/covers/'),
        ),
        migrations.AlterField(
            model_name='community',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='community_service/community_app/profiles/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, null=True),
        ),
    ]
