USER_SERVICE_URL = "http://host.docker.internal:8001"
ARTICLE_SERVICE_URL = "http://host.docker.internal:8002"
COMMUNITY_SERVICE_URL = "http://host.docker.internal:8003"
TEAM_SERVICE_URL = "http://host.docker.internal:8004"
COMMUNICATION_SERVICE_URL = "http://host.docker.internal:8005"