# Generated by Django 5.0.6 on 2024-07-04 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0002_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='thumbnails/'),
        ),
    ]
