# Generated by Django 5.0.6 on 2024-07-11 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0006_comment_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set(),
        ),
    ]
