# Generated by Django 5.0.6 on 2024-07-22 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0012_article_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='article_app.article')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='article_app.interest')),
            ],
        ),
    ]
