# Generated by Django 5.0.6 on 2024-07-22 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0013_remove_article_tags_tag'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('article', 'interest')},
        ),
    ]
