# Generated by Django 5.0.6 on 2024-07-29 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0015_alter_tag_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='community_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
