# Generated by Django 5.0.6 on 2024-08-18 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0017_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='article_service/article_app/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='article_service/article_app/profiles/'),
        ),
    ]
