# Generated by Django 5.0.6 on 2024-08-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0018_alter_article_thumbnail_alter_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile',
            field=models.CharField(blank=True, null=True),
        ),
    ]
