# Generated by Django 5.0.6 on 2024-08-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0021_articleview_userinterest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
