# Generated by Django 5.0.6 on 2024-08-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0022_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
