# Generated by Django 5.0.6 on 2024-08-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0023_article_is_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_toxic',
            field=models.BooleanField(default=False),
        ),
    ]
