# Generated by Django 5.0.6 on 2024-08-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0024_article_is_toxic'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='toxicity_score',
            field=models.FloatField(default=0.0),
        ),
    ]
