name: CI/CD Pipeline

# on:
#   push:
#     branches:
#       - main  
#   pull_request:
#     branches:
#       - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Services
      run: |
        docker buildx build --push --tag fauzu/wimble-api_gateway:latest ./server/api_gateway
        docker buildx build --push --tag fauzu/wimble-user_service:latest ./server/user_service
        docker buildx build --push --tag fauzu/wimble-article_service:latest ./server/article_service
        docker buildx build --push --tag fauzu/wimble-community_service:latest ./server/community_service
        docker buildx build --push --tag fauzu/wimble-team_service:latest ./server/team_service
        docker buildx build --push --tag fauzu/wimble-communication_service:latest ./server/communication_service
        docker buildx build --push --tag fauzu/wimble-payment_service:latest ./server/payment_service

    - name: Cleanup
      run: docker logout